# Generated by Django 4.2.3 on 2023-07-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ManyToManyField(related_name='albums', to='Tracks.genre'),
        ),
    ]
