# Generated by Django 4.2.3 on 2023-07-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0002_remove_genre_album_album_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
    ]
