# Generated by Django 4.2.3 on 2023-07-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0003_remove_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(default=None, upload_to='tracks/tracks'),
            preserve_default=False,
        ),
    ]
