# Generated by Django 4.2.3 on 2023-07-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0004_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=None, upload_to='tracks/albums'),
            preserve_default=False,
        ),
    ]
