# Generated by Django 4.2.3 on 2023-07-31 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0005_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
    ]
