# Generated by Django 4.2.3 on 2023-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0009_album_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default=None, upload_to='tracks/genres'),
            preserve_default=False,
        ),
    ]
