# Generated by Django 4.2.3 on 2023-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0010_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(null=True, upload_to='tracks/genres'),
        ),
    ]
