# Generated by Django 4.2.3 on 2023-07-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0011_alter_genre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
