# Generated by Django 4.2.1 on 2023-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0015_remove_album_album_album_genre_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(related_name='albums', to='Tracks.genre'),
        ),
    ]
