# Generated by Django 4.2.1 on 2023-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0016_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='Tracks.genre'),
        ),
    ]
